### ISSUE TITLE
Help me ModuleNotFoundError: No module named 'websocket'

### ISSUE THREAD

**Issue by sujinda123** [Lu-Yi-Hsun/iqoptionapi#66] opened 2018-12-25 12:44 UTC
<img style="-webkit-user-select: none;cursor: zoom-in;" src="https://i.imgur.com/SG35gZL.png" width="586" height="399">

Please also recommend

**Comment by JafferWilson** [comment] 2018-12-25 13:14
Then please install it.
`pip install websocket`

**Comment by sujinda123** [comment] 2018-12-25 13:34
Yeah i can do
But there are still errors

<img style="-webkit-user-select: none;cursor: zoom-out;" src="https://i.imgur.com/IGeA0ay.png" width="1179" height="1401">

**Comment by JafferWilson** [comment] 2018-12-25 13:36
What is your Python version? Please mention it. The issue might be because you are using Python 2

**Comment by sujinda123** [comment] 2018-12-25 13:42
<img style="-webkit-user-select: none;cursor: zoom-out;" src="https://i.imgur.com/2d01UoD.png" width="1172" height="1292">

Now I use Python 3.

**Comment by Lu-Yi-Hsun** [comment] 2018-12-25 13:49
i find the problem , please 
```
pip uninstall websocket
```

**Comment by Lu-Yi-Hsun** [comment] 2018-12-25 13:56
wait me update last version to avoid that again

**Comment by sujinda123** [comment] 2018-12-25 14:16
I successfully uninstalled

**Comment by Lu-Yi-Hsun** [comment] 2018-12-25 14:18
websocket-client and websocket are conflict, i will write done on README.md

**Comment by sujinda123** [comment] 2018-12-25 14:59
Yeah, I can connect successfully.
Thank you for your advice
The opportunity to face when I have a problem will come to ask again.

**Comment by JafferWilson** [comment] 2018-12-26 05:57
@sujinda123 If the issue is resolved please close it. It helps.

**Closed** 2019-01-26 03:19 UTC

**Comment by zinken7** [comment] 2019-10-10 17:36
Can you help me?
I have same issue even used fix way
<img width="1172" alt="Screen Shot 2019-10-11 at 12 31 34 AM" src="https://user-images.githubusercontent.com/56407861/66592366-167bbe00-ebbf-11e9-9f3f-785aa85a4edf.png">

**Comment by Lu-Yi-Hsun** [comment] 2019-10-10 20:34
pip uninstall websocket-client
pip uninstall websocket
pip install websocket-client==0.47

**Comment by zinken7** [comment] 2019-10-11 02:27
Its work. Thanks. I almost use pip3.

**Comment by sasori107** [comment] 2025-03-24 06:19
I am having problems operating in the normal market in these assets "EURUSD", "GBPUSD", "EURGBP", it is only operating in OTC.

python 3.8.19
iqoptionapi 7.1.1
websocket-client 0.56.0

2025-03-24 01:13:12,707 ERROR:El activo EURUSD no est� disponible para operar en este momento.
2025-03-24 01:13:12,707 ERROR:El activo EURUSD est� suspendido. Orden no ejecutada.
2025-03-24 01:13:12,707 ERROR:No se pudo abrir la orden para EURUSD

2025-03-24 01:14:12,177 ERROR:El activo GBPUSD no est� disponible para operar en este momento.
2025-03-24 01:14:12,177 ERROR:El activo GBPUSD est� suspendido. Orden no ejecutada.
2025-03-24 01:14:12,177 ERROR:No se pudo abrir la orden para GBPUSD
